apiVersion: v1
kind: PersistentVolume
metadata:
  name: sgw-claim3
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: sgw-claim3
  hostPath:
    path: "/etc/localtime"