apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodbdata
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: mongodbdata
  hostPath:
    path: "/var/lib/mongodb"