apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ubuntu/docker_open5gs/docker-compose.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: dns
  name: dns
spec:
  ports:
    - name: "53"
      port: 53
      protocol: UDP
      targetPort: 53
  selector:
    io.kompose.service: dns
status:
  loadBalancer: {}
