apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ubuntu/docker_open5gs/docker-compose.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: fhoss
  name: fhoss
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
  selector:
    io.kompose.service: fhoss
status:
  loadBalancer: {}
