apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ubuntu/docker_open5gs/docker-compose.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: pgw
  name: pgw
spec:
  ports:
    - name: "3868"
      port: 3868
      protocol: UDP
      targetPort: 3868
    - name: 3868-tcp
      port: 3868
      targetPort: 3868
    - name: 3868-sctp
      port: 3868
      protocol: SCTP
      targetPort: 3868
    - name: "5868"
      port: 5868
      protocol: UDP
      targetPort: 5868
    - name: 5868-tcp
      port: 5868
      targetPort: 5868
    - name: 5868-sctp
      port: 5868
      protocol: SCTP
      targetPort: 5868
    - name: "2152"
      port: 2152
      protocol: UDP
      targetPort: 2152
    - name: "2123"
      port: 2123
      protocol: UDP
      targetPort: 2123
  selector:
    io.kompose.service: pgw
status:
  loadBalancer: {}
