apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ubuntu/docker_open5gs/docker-compose.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: rtpengine
  name: rtpengine
spec:
  ports:
    - name: "2223"
      port: 2223
      protocol: UDP
      targetPort: 2223
    # - name: "0"
    #   port: 0
    #   protocol: UDP
    #   targetPort: 0
  selector:
    io.kompose.service: rtpengine
status:
  loadBalancer: {}
