apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f /home/ubuntu/docker_open5gs/docker-compose.yaml
    kompose.version: 1.25.0 (a70f80cc)
  creationTimestamp: null
  labels:
    io.kompose.service: sgw
  name: sgw
spec:
  ports:
    - name: "2123"
      port: 2123
      protocol: UDP
      targetPort: 2123
    - name: "2152"
      port: 2152
      protocol: UDP
      targetPort: 2152
  selector:
    io.kompose.service: sgw
status:
  loadBalancer: {}
