apiVersion: v1
kind: PersistentVolume
metadata:
  name: rtpengine-claim2
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: rtpengine-claim2
  hostPath:
    path: "/etc/localtime"