apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcrf-claim1
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: pcrf-claim1
  hostPath:
    path: "/open5gs/install/var/log/open5gs"