apiVersion: v1
kind: PersistentVolume
metadata:
  name: pcrf-claim0
  labels:
    type: local
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  claimRef:
    namespace: default
    name: pcrf-claim0
  hostPath:
    path: "/mnt/pcrf"